ACCOUNTS = [ "GCI656BG2ZIJ5JJM23C5BUEZU27ZIZJTTYQQLI7KALOLLMDH4P6F265Y" ]
VERSION = "0.1.0"
SIGNING_KEY = "GBESIPYS2WBWIDVTODT5KTVL6JPUGJBM66ZJHEJ5ZIGYZXPEVTAG7NCA"
NETWORK_PASSPHRASE = "Standalone Network ; February 2017"

TRANSFER_SERVER = "https://127.0.0.1:9002/sep6"
TRANSFER_SERVER_SEP0024 = "https://127.0.0.1:9002/sep24"
WEB_AUTH_ENDPOINT = "https://127.0.0.1:9002/auth"
KYC_SERVER = "https://127.0.0.1:9002/kyc"
DIRECT_PAYMENT_SERVER = "https://127.0.0.1:9002/sep31"


[[CURRENCIES]]
code = "eFCFA"
issuer = "GDA5SITSDHCFLAPZBGKVHUMSVC4B7LNDYGPBIPVMTU64FELDNWVIXQK5"
status = "test"
is_asset_anchored = false
anchor_asset_type = "other"
desc = "A fake anchored asset to use with this example anchor server."


