# version: "3"

# services:
#   server:
#     container_name: "test-server"
#     build: .
#     volumes:
#       - ./data:/home/data
#     ports:
#       - "9000:9000"
#     command: python3 app/manage.py runsslerver 127.0.0.1:9000
#   execute_outgoing_transactions:
#     container_name: "test-execute_outgoing_transactions"
#     build: .
#     volumes:
#       - ./data:/home/data
#     command: python3 app/manage.py execute_outgoing_transactions --loop
#   check_trustlines:
#     container_name: "test-check_trustlines"
#     build: .
#     volumes:
#       - ./data:/home/data
#     command: python3 app/manage.py check_trustlines --loop
#   watch_transaction:
#     container_name: "test-watch_transactions"
#     build: .
#     volumes:
#       - ./data:/home/data
#     command: python3 app/manage.py watch_transactions
#   poll_pending_deposits:
#     container_name: "test-poll_pending_deposits"
#     build: .
#     volumes:
#       - ./data:/home/data
#     command: python3 app/manage.py poll_pending_deposits --loop